name: student_helper_app
description: A new Flutter project for student homework and exam management.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  timezone: ^0.10.0
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  flutter_facebook_auth: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\splash_logo.jpg

flutter_native_splash:
  color: "#252525"  # Background color (gray)
  image: assets/splash_logo.jpg  # Your logo (make sure it exists)
  android: true
  ios: true
  android_12:
    color: "#252525"
    image: assets\splash_logo.jpg